import { Geist, Geist_Mono,Jersey_10} from "next/font/google";
import "./globals.css";

const jersey10 = Jersey_10({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
  variable : "--font-jersey10",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${jersey10.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}
